"""
Generates a tiny base64 LQIP for every photographic slot.

Next/Image can show a blurred placeholder while the real file streams in, but
only if it is given `blurDataURL`. Without it images pop in abruptly, which is
what reads as "slow loading" even when the bytes are fine.

Each placeholder is a 10px-wide JPEG — roughly 300-500 bytes — so the whole set
adds a few KB to the bundle and removes every pop-in on the site.

Run:  python scripts/generate-blur.py
"""
from PIL import Image
import base64, io, os, re, pathlib

REG = pathlib.Path("src/lib/images.ts")
src = REG.read_text(encoding="utf-8")

# Every distinct /images/*.jpg referenced by the registry.
files = sorted(set(re.findall(r'"(/images/[a-z0-9\-]+\.jpg)"', src)))

out = {}
for ref in files:
    path = pathlib.Path("public" + ref)
    if not path.exists():
        continue
    im = Image.open(path).convert("RGB")
    w = 8
    im = im.resize((w, max(1, round(w * im.height / im.width))), Image.LANCZOS)
    buf = io.BytesIO()
    im.save(buf, "JPEG", quality=28)
    out[ref] = "data:image/jpeg;base64," + base64.b64encode(buf.getvalue()).decode()

lines = [
    "/**",
    " * AUTO-GENERATED by scripts/generate-blur.py — do not edit by hand.",
    " *",
    " * A 10px LQIP per photograph, used as next/image `blurDataURL`. Without a",
    " * placeholder, images pop in as they decode, which reads as slow loading",
    " * even when the transfer is fast.",
    " */",
    "",
    "export const blurDataUrls: Record<string, string> = {",
]
for k, v in out.items():
    lines.append(f'  "{k}": "{v}",')
lines += ["};", ""]

dest = pathlib.Path("src/lib/blur.ts")
dest.write_text("\n".join(lines), encoding="utf-8")
total = sum(len(v) for v in out.values())
print(f"{len(out)} placeholders -> {dest}  ({total/1024:.1f} KB inline)")
